title: Brianna Chen Portfolio
email: blchen@mitre.org
description: >- # this means to ignore newlines until "baseurl:"
  Brianna Chen Portfolio
baseurl: "" # the subpath of your site
url: "" # the base hostname & protocol for your site, e.g. http://example.com
